"use client";
import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Boxes, Check, LayoutDashboard, MapPin, Menu, PackageCheck, RefreshCw, Search, Settings, ShoppingBag, Store, X } from "lucide-react";
type View="dashboard"|"inventory"|"orders"|"sync"|"settings";
type Status={ready:boolean;ebayConfigured:boolean;ebayAppConfigured?:boolean;supabaseConfigured:boolean;listings?:number;physical?:number;orders?:number;issues?:number;lastSync?:string|null;orderRows?:any[];error?:string};
type Listing={id:string;ebay_listing_id:string;ebay_sku:string|null;title:string;game:string;set_name:string|null;price:number|null;ebay_quantity:number;physical_skus:any[]};
const nav=[["dashboard","Dashboard",LayoutDashboard],["inventory","Inventory",Boxes],["orders","Orders",ShoppingBag],["sync","Sync Status",RefreshCw],["settings","Settings",Settings]] as const;
export default function Home(){
 const[view,setView]=useState<View>("dashboard"),[mobile,setMobile]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState<Status>({ready:false,ebayConfigured:false,supabaseConfigured:false}),[inventory,setInventory]=useState<Listing[]>([]),[orders,setOrders]=useState<any[]>([]),[q,setQ]=useState(""),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const s:any=await fetch("/api/status",{cache:"no-store"}).then(r=>r.json());setStatus(s)},[]);
 const loadInventory=useCallback(async(search:string,currentPage:number)=>{setLoading(true);try{const b:any=await fetch(`/api/inventory?q=${encodeURIComponent(search)}&page=${currentPage}&pageSize=50`,{cache:"no-store"}).then(r=>r.json());if(b.error)throw new Error(b.error);setInventory(b.rows||[]);setTotal(b.total||0)}catch(e){setMessage(e instanceof Error?e.message:"Inventory failed")}finally{setLoading(false)}},[]);
 const loadOrders=useCallback(async()=>{setLoading(true);try{const b:any=await fetch("/api/orders",{cache:"no-store"}).then(r=>r.json());if(b.error)throw new Error(b.error);setOrders(b.rows||[])}catch(e){setMessage(e instanceof Error?e.message:"Orders failed")}finally{setLoading(false)}},[]);
 useEffect(()=>{const p=new URLSearchParams(location.search);if(p.get("ebay")==="connected")setMessage("eBay connected. You can now import your real listings and orders.");if(p.get("ebay_error"))setMessage(p.get("ebay_error")||"");load().catch(e=>setMessage(e.message))},[load]);
 useEffect(()=>{if(view!=="inventory"||!status.ready)return;const timer=setTimeout(()=>loadInventory(q,page),q?350:0);return()=>clearTimeout(timer)},[view,status.ready,q,page,loadInventory]);
 useEffect(()=>{if(view==="orders"&&status.ready)loadOrders()},[view,status.ready,loadOrders]);
 const sync=async()=>{if(!confirm("Import current active listings and open orders from eBay into the fresh Supabase database? This reads eBay only and will NOT change any eBay listing."))return;setBusy(true);setMessage("");try{const r=await fetch("/api/sync",{method:"POST"});const b:any=await r.json();if(!r.ok)throw new Error(b.error||"Sync failed");setMessage(b.warning||`Imported ${b.listings.toLocaleString()} active listings and ${b.orders.toLocaleString()} order lines.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Sync failed")}finally{setBusy(false)}};
 return <div className="shell"><aside className={mobile?"open":""}><div className="logo"><span>◓</span><div><b>SWIVELS</b><small>INVENTORY</small></div><button onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([id,label,I])=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setMobile(false)}}><I/><span>{label}</span>{id==="orders"&&Boolean(status.orders)&&<i>{status.orders}</i>}</button>)}</nav><div className="master"><Store/><div><small>MASTER SOURCE</small><b>eBay</b><em>{status.ebayConfigured?"● OAuth connected":"○ Not connected"}</em></div></div><div className="profile"><span>SC</span><div><b>Swivels</b><small>Card Shop</small></div></div></aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)}/>}<main><header><button className="menubtn" onClick={()=>setMobile(true)}><Menu/></button><div><small>SWIVELS CARD SHOP</small><h1>{nav.find(x=>x[0]===view)?.[1]}</h1></div><div className="head"><span>{status.lastSync?`Last eBay import ${new Date(status.lastSync).toLocaleString()}`:"Never imported"}</span>{status.ebayConfigured?<button className="primary" disabled={busy||!status.ready} onClick={sync}><RefreshCw className={busy?"spin":""}/>{busy?"Importing…":"Import from eBay"}</button>:<a className="primary" href="/api/ebay/connect">Connect eBay</a>}</div></header><div className="content">{message&&<div className="notice">{message}</div>}{status.error&&<div className="warning"><AlertTriangle/><div><b>Setup required</b><p>{status.error}</p></div></div>}{view==="dashboard"&&<Dashboard s={status} go={setView}/>} {view==="inventory"&&<Inventory rows={inventory} q={q} setQ={v=>{setQ(v);setPage(1)}} page={page} setPage={setPage} total={total} loading={loading}/>} {view==="orders"&&<Orders rows={orders} loading={loading}/>} {view==="sync"&&<Sync s={status} busy={busy} sync={sync}/>} {view==="settings"&&<Connections s={status}/>}</div></main></div>}
function Intro({title,text,action}:{title:string;text:string;action?:React.ReactNode}){return <div className="intro"><div><h2>{title}</h2><p>{text}</p></div>{action}</div>}
function Metric({n,t,d}:{n:number|string;t:string;d:string}){return <article><Store/><div><small>{t}</small><b>{typeof n==="number"?n.toLocaleString():n}</b><em>{d}</em></div></article>}
function Dashboard({s,go}:{s:Status;go:(v:View)=>void}){const connected=s.ready&&s.ebayConfigured;return <><Intro title="eBay is the master. Supabase stores the working catalog." text="All numbers below come from your connected Supabase project." action={<span className={connected?"healthy":"count"}>{connected?<><Check/> Ready for eBay import</>:"Setup incomplete"}</span>}/><div className="metrics"><Metric n={s.listings||0} t="Active eBay listings" d="Imported master catalog"/><Metric n={s.physical||0} t="Physical SKU locations" d="Stored in Supabase"/><Metric n={s.orders||0} t="Ready to pull" d="Open, non-refunded orders"/><Metric n={s.issues||0} t="Needs review" d="Reconciliation issues"/></div><div className="grid"><section className="panel"><Title k="REAL DATA STATUS" t={s.lastSync?"Latest import completed":"No eBay data imported yet"}/><Connection name="eBay" detail={s.ebayConfigured?"OAuth refresh token stored securely":"Use Connect eBay to authorize"} ok={s.ebayConfigured}/><Connection name="Supabase" detail={s.ready?"Schema connected":"Not ready"} ok={s.ready}/></section><section className="panel links"><Title k="SAFE IMPORT" t="eBay remains read-only"/><p className="bodycopy">Import reads active listings and open orders from eBay, then stores them in Supabase. It never revises, ends, or changes an eBay listing.</p>{!s.ebayConfigured&&<a className="primary" href="/api/ebay/connect">Connect eBay</a>}</section></div><section className="panel"><Title k="FULFILLMENT" t="Recent orders" on={()=>go("orders")}/>{(s.orderRows||[]).length?(s.orderRows||[]).map((o:any)=><Mini key={o.id} order={o}/>):<Empty text="No real open orders have been imported."/>}</section></>}
function Connection({name,detail,ok}:{name:string;detail:string;ok:boolean}){return <div className="connection"><span>{name[0]}</span><div><b>{name}</b><small>{detail}</small></div><em>{ok?"● Connected":"○ Offline"}</em></div>}
function Title({k,t,on}:{k:string;t:string;on?:()=>void}){return <div className="title"><div><small>{k}</small><h3>{t}</h3></div>{on&&<button onClick={on}>Review all</button>}</div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function Mini({order}:{order:any}){return <div className="mini"><PackageCheck/><div><b>{order.marketplace_listings?.title||"eBay order"}</b><small>Order #{order.marketplace_order_id}</small></div><div><small>QUANTITY</small><b>{order.quantity}</b></div></div>}
function Inventory({rows,q,setQ,page,setPage,total,loading}:{rows:Listing[];q:string;setQ:(v:string)=>void;page:number;setPage:(v:number)=>void;total:number;loading:boolean}){const pages=Math.max(1,Math.ceil(total/50));return <div className="stack"><Intro title="Inventory" text="Only 50 records are downloaded at a time to keep Supabase usage low." action={<span className="count">{total.toLocaleString()} listings</span>}/><div className="toolbar"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search title, eBay SKU, or listing ID…"/></label></div><div className="tablebox"><table><thead><tr><th>Card</th><th>Game</th><th>eBay listing</th><th>eBay SKU</th><th>eBay qty</th><th>Physical locations</th><th>Price</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.title}</b><small>{x.set_name||"Set not imported"}</small></td><td>{x.game}</td><td className="mono">{x.ebay_listing_id}</td><td className="mono">{x.ebay_sku||"—"}</td><td><strong>{x.ebay_quantity}</strong></td><td><div className="skus">{x.physical_skus?.length?x.physical_skus.map((s:any)=><span key={s.sku}>{s.location_label||s.sku}</span>):<span>Not assigned</span>}</div></td><td>{x.price==null?"—":`$${Number(x.price).toFixed(2)}`}</td></tr>)}</tbody></table>{loading?<Empty text="Loading inventory…"/>:!rows.length&&<Empty text="No listings match this search."/>}</div><div className="pager"><button className="secondary" disabled={loading||page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page.toLocaleString()} of {pages.toLocaleString()}</span><button className="secondary" disabled={loading||page>=pages} onClick={()=>setPage(page+1)}>Next</button></div></div>}
function Orders({rows,loading}:{rows:any[];loading:boolean}){return <div className="stack"><Intro title="Orders to fulfill" text="Only real open, non-refunded eBay orders imported into Supabase." action={<span className="count">Up to 50 order lines</span>}/>{loading?<Empty text="Loading orders…"/>:<><div className="ordergrid">{rows.map(o=>{const l=o.marketplace_listings;const sku=l?.physical_skus?.find((x:any)=>x.status==="available")||l?.physical_skus?.[0];return <article className="order" key={o.id}><div className="ordertop"><span>eBay</span><small>{new Date(o.ordered_at).toLocaleString()}</small></div><h3>{l?.title||"Unmatched eBay listing"}</h3><p>Order #{o.marketplace_order_id} · Quantity {o.quantity}</p><div className="location"><small>PULL LOCATION</small><b><MapPin/>{sku?.location_label||l?.ebay_sku||"No physical location"}</b></div></article>})}</div>{!rows.length&&<Empty text="No real open orders have been imported."/>}</>}</div>}
function Sync({s,busy,sync}:{s:Status;busy:boolean;sync:()=>void}){return <div className="stack"><Intro title="Safe eBay import" text="Reads eBay and updates only the fresh Supabase database." action={<button className="primary" disabled={busy||!s.ready||!s.ebayConfigured} onClick={sync}><RefreshCw className={busy?"spin":""}/>{busy?"Importing…":"Import from eBay"}</button>}/><div className="flow">{[["1","Read eBay","No eBay changes"],["2","Update Supabase","Listings and orders"],["3","Show results","Real records only"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div><div className="warning"><AlertTriangle/><div><b>Initial import safety</b><p>If eBay returns zero listings or an authorization error, the database is not changed. This version has no code that revises or ends an eBay listing.</p></div></div></div>}
function Connections({s}:{s:Status}){return <div className="stack"><Intro title="Connections" text="App credentials stay in Render; the eBay refresh token is saved securely in Supabase." action={!s.ebayConfigured?<a className="primary" href="/api/ebay/connect">Connect eBay</a>:undefined}/><div className="setupgrid two"><Setup title="eBay" ok={s.ebayConfigured} text="OAuth authorization with an automatically renewed access token"/><Setup title="Supabase" ok={s.supabaseConfigured&&s.ready} text="SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY"/></div><div className="warning"><AlertTriangle/><div><b>eBay developer settings</b><p>Render needs EBAY_CLIENT_ID, EBAY_CLIENT_SECRET, and EBAY_RU_NAME. You do not need to copy a short-lived access token.</p></div></div></div>}
function Setup({title,ok,text}:{title:string;ok:boolean;text:string}){return <article className="setup"><Store/><h3>{title}</h3><p>{text}</p><span className={ok?"healthy":"count"}>{ok?"Connected":"Not configured"}</span></article>}
