"use client";
import {useMemo,useState} from "react";
import {AlertTriangle,Boxes,Check,ChevronRight,LayoutDashboard,MapPin,Menu,PackageCheck,RefreshCw,Search,Settings,ShoppingBag,Store,WandSparkles,X} from "lucide-react";
type View="dashboard"|"inventory"|"orders"|"magic"|"sync"|"settings";
const nav=[["dashboard","Dashboard",LayoutDashboard],["inventory","Inventory",Boxes],["orders","Orders",ShoppingBag],["magic","Magic Sync",WandSparkles],["sync","Sync Status",RefreshCw],["settings","Settings",Settings]] as const;
const cards=[
 {title:"Charizard ex 125/197",set:"Obsidian Flames",game:"Pokémon",id:"145917283640",qty:3,skus:["Box-A-12-023","Box-B-04-018","Box-C-09-041"],price:"$4.95",status:"matched"},
 {title:"Mewtwo 056/172 Reverse Holo",set:"Brilliant Stars",game:"Pokémon",id:"145917284104",qty:2,skus:["Box-A-37-009"],price:"$1.49",status:"missing"},
 {title:"Heat Factory ◇",set:"Celestial Storm",game:"Pokémon",id:"145917287211",qty:2,skus:["Box-A-23-014","Box-A-13-004","Box-B-02-119"],price:"$2.25",status:"extra"},
 {title:"Sol Ring — Borderless",set:"Commander Masters",game:"Magic",id:"145917288902",qty:1,skus:["Box-M-08-044"],price:"$3.79",status:"matched"}];
const orders=[{id:"24-11892-53017",item:"Charizard ex 125/197",loc:"Box-A-12-023",market:"eBay",age:"8 min"},{id:"24-11891-90742",item:"Sol Ring — Borderless",loc:"Box-M-08-044",market:"Manapool",age:"21 min"}];
function Pill({s}:{s:string}){return <span className={"pill "+s}>{s==="matched"?"● Matched":s==="missing"?"▲ 1 SKU missing":"▲ 1 extra SKU"}</span>}
export default function Home(){
 const[v,setV]=useState<View>("dashboard"),[q,setQ]=useState(""),[mobile,setMobile]=useState(false),[busy,setBusy]=useState(false),[toast,setToast]=useState("");
 const filtered=useMemo(()=>cards.filter(x=>(x.title+x.set+x.skus.join(" ")).toLowerCase().includes(q.toLowerCase())),[q]);
 const sync=()=>{setBusy(true);setTimeout(()=>{setBusy(false);setToast("Reconciliation finished — 2 items need review");setTimeout(()=>setToast(""),3200)},1100)};
 return <div className="shell"><aside className={mobile?"open":""}><div className="logo"><span>◓</span><div><b>SWIVELS</b><small>INVENTORY</small></div><button onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([id,label,I])=><button key={id} className={v===id?"active":""} onClick={()=>{setV(id);setMobile(false)}}><I/><span>{label}</span>{id==="orders"&&<i>2</i>}</button>)}</nav><div className="master"><Store/><div><small>MASTER SOURCE</small><b>eBay</b><em>● Connected</em></div></div><div className="profile"><span>KN</span><div><b>Kevin</b><small>Swivels Card Shop</small></div></div></aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)}/>}
 <main><header><button className="menubtn" onClick={()=>setMobile(true)}><Menu/></button><div><small>SWIVELS CARD SHOP</small><h1>{nav.find(x=>x[0]===v)?.[1]}</h1></div><div className="head"><span>Last eBay sync <b>2 min ago</b></span><button className="primary" onClick={sync}><RefreshCw className={busy?"spin":""}/>{busy?"Syncing…":"Sync now"}</button></div></header><div className="content">
 {v==="dashboard"&&<Dashboard go={setV} sync={sync}/>}
 {v==="inventory"&&<Inventory rows={filtered} q={q} setQ={setQ}/>}
 {v==="orders"&&<Orders/>}{v==="magic"&&<Magic/>}{v==="sync"&&<Sync sync={sync} busy={busy}/>}
 {v==="settings"&&<Connections/>}</div></main>{toast&&<div className="toast"><Check/>{toast}</div>}</div>
}
function Intro({title,text,action}:{title:string,text:string,action?:React.ReactNode}){return <div className="intro"><div><h2>{title}</h2><p>{text}</p></div>{action}</div>}
function Dashboard({go,sync}:{go:(x:View)=>void,sync:()=>void}){return <><Intro title="eBay is the master. Everything else stays in line." text="Inventory control center" action={<span className="healthy"><Check/> Core sync healthy</span>}/><div className="metrics"><Metric n="6,194" t="Active eBay listings" d="Master catalog"/><Metric n="6,207" t="Physical cards" d="Across SKU locations"/><Metric n="2" t="Ready to pull" d="Unfulfilled orders"/><Metric n="428" t="Magic linked" d="eBay ↔ Manapool"/></div><div className="grid"><section className="panel"><Title k="EBAY MASTER RECONCILIATION" t="2 items need your attention" on={()=>go("sync")}/><div className="progress"><i/><b>6,192 / 6,194 matched</b></div><Issue t="Missing physical location" c="Mewtwo 056/172 Reverse Holo" d="eBay 2 · Supabase 1"/><Issue t="Extra Supabase SKU" c="Heat Factory ◇" d="eBay 2 · Supabase 3"/></section><section className="panel links"><Title k="CONNECTIONS" t="Marketplace status"/>{[["eBay","Master · 6,194 listings"],["Supabase","SKU locations · Connected"],["Manapool","Magic only · 428 linked"]].map(x=><div className="connection" key={x[0]}><span>{x[0][0]}</span><div><b>{x[0]}</b><small>{x[1]}</small></div><em>● Live</em></div>)}<button className="secondary" onClick={sync}><RefreshCw/>Run full reconciliation</button></section></div><div className="grid lower"><section className="panel"><Title k="FULFILLMENT" t="Orders ready to pull" on={()=>go("orders")}/>{orders.map(o=><div className="mini" key={o.id}><PackageCheck/><div><b>{o.item}</b><small>{o.market} · {o.age} ago</small></div><div><small>PULL FROM</small><b><MapPin/>{o.loc}</b></div></div>)}</section><section className="panel"><Title k="RECENT ACTIVITY" t="Sync feed"/>{["eBay catalog reconciliation completed","Order assigned to Box-A-12-023","Manapool quantity updated to 1"].map((x,i)=><div className="feed" key={x}><i/><div><b>{x}</b><small>12:{42-i*3} PM</small></div></div>)}</section></div></>}
function Metric({n,t,d}:{n:string,t:string,d:string}){return <article><Store/><div><small>{t}</small><b>{n}</b><em>{d}</em></div></article>}
function Title({k,t,on}:{k:string,t:string,on?:()=>void}){return <div className="title"><div><small>{k}</small><h3>{t}</h3></div>{on&&<button onClick={on}>Review all <ChevronRight/></button>}</div>}
function Issue({t,c,d}:{t:string,c:string,d:string}){return <div className="issue"><span><AlertTriangle/></span><div><b>{t}</b><small>{c}</small></div><em>{d}</em><ChevronRight/></div>}
function Inventory({rows,q,setQ}:{rows:typeof cards,q:string,setQ:(x:string)=>void}){return <div className="stack"><Intro title="Inventory" text="eBay quantity is authoritative. Physical SKUs show where each copy lives."/><div className="toolbar"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search card, set, listing ID, or SKU…"/></label><select><option>All games</option><option>Pokémon</option><option>Magic</option></select><select><option>All statuses</option><option>Matched</option><option>Needs review</option></select></div><div className="tablebox"><table><thead><tr><th>Card</th><th>Game</th><th>eBay listing</th><th>eBay qty</th><th>Physical SKUs</th><th>Price</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.title}</b><small>{x.set}</small></td><td>{x.game}</td><td className="mono">{x.id}</td><td><strong>{x.qty}</strong></td><td><div className="skus">{x.skus.map(s=><span key={s}>{s}</span>)}</div></td><td>{x.price}</td><td><Pill s={x.status}/></td></tr>)}</tbody></table></div></div>}
function Orders(){return <div className="stack"><Intro title="Orders to fulfill" text="Only open, non-refunded orders. Each card is assigned to one physical location." action={<span className="count">2 ready</span>}/><div className="ordergrid">{orders.map(o=><article className="order" key={o.id}><div className="ordertop"><span>{o.market}</span><small>{o.age} ago</small></div><h3>{o.item}</h3><p>Order #{o.id}</p><div className="location"><small>PULL LOCATION</small><b><MapPin/>{o.loc}</b></div><button className="primary wide"><PackageCheck/>Mark pulled</button></article>)}</div></div>}
function Magic(){return <div className="stack"><Intro title="Magic Sync" text="Manapool mirrors the eBay-master quantity for linked Magic cards."/><div className="rule"><Store/><div><b>eBay remains the master</b><p>A Manapool sale reduces eBay first. The new eBay quantity then reconciles Supabase and Manapool.</p></div></div><div className="metrics compact"><Metric n="431" t="Magic eBay listings" d=""/><Metric n="428" t="Linked to Manapool" d=""/><Metric n="3" t="Needs mapping" d=""/></div><section className="panel"><Title k="QUANTITY CHECK" t="Recent linked cards"/>{["Sol Ring — Borderless","Counterspell — Retro Frame","Arcane Signet — Foil"].map((x,i)=><div className="maprow" key={x}><div><b>{x}</b><small>Magic · Commander</small></div><span>eBay <b>{i===2?2:1}</b></span><ChevronRight/><span>Manapool <b>{i===2?2:1}</b></span><Pill s="matched"/></div>)}</section></div>}
function Sync({sync,busy}:{sync:()=>void,busy:boolean}){return <div className="stack"><Intro title="Reconciliation" text="Every check starts with eBay and compares Supabase locations against it." action={<button className="primary" onClick={sync}><RefreshCw className={busy?"spin":""}/>{busy?"Running…":"Run reconciliation"}</button>}/><div className="flow">{[["1","Read eBay","Listings + quantities"],["2","Compare Supabase","Active physical SKUs"],["3","Flag differences","Never alter eBay"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small><ChevronRight/></div>)}</div><section className="panel"><Title k="REQUIRES REVIEW" t="2 reconciliation issues"/>{cards.filter(x=>x.status!=="matched").map(x=><div className="review" key={x.id}><Pill s={x.status}/><div><b>{x.title}</b><small>{x.id} · eBay quantity {x.qty} · {x.skus.length} active SKUs</small></div><button>Review <ChevronRight/></button></div>)}</section></div>}
function Connections(){return <div className="stack"><Intro title="Connections" text="Add credentials for this fresh system. No old Supabase records will be imported."/><div className="setupgrid"><Setup title="eBay" text="Listings, orders, CSV-created SKUs, and notifications" fields={["Client ID","Client secret","Refresh token"]}/><Setup title="Supabase" text="Fresh physical SKU locations and marketplace links" fields={["Project URL","Service role key"]}/><Setup title="Manapool" text="Magic-only listings and orders" fields={["API URL","API key"]}/></div><div className="warning"><AlertTriangle/><div><b>Fresh-start protection</b><p>The system creates a new schema only. It does not migrate, repair, or reuse the previous inventory.</p></div></div></div>}
function Setup({title,text,fields}:{title:string,text:string,fields:string[]}){return <article className="setup"><Store/><h3>{title}</h3><p>{text}</p>{fields.map(f=><label key={f}><small>{f}</small><input type={/secret|key|token/i.test(f)?"password":"text"} placeholder={"Enter "+f.toLowerCase()}/></label>)}<button className="secondary">Connect {title}</button></article>}
